-- +goose Up
INSERT INTO audit_log_type (id, code, name, created_at, updated_at) VALUES
(1, 'USER_LOGIN', 'ユーザーログイン', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'USER_LOGOUT', 'ユーザーログアウト', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'PASSWORD_CHANGE', 'パスワード変更', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'USER_CREATE', 'ユーザー作成', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'USER_UPDATE', 'ユーザー更新', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'USER_DELETE', 'ユーザー削除', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'ROLE_ASSIGN', 'ロール割り当て', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'ROLE_UPDATE', 'ロール変更', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'TRANSACTION_BUSINESS_APPROVED', '取引承認（事業）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'TRANSACTION_BUSINESS_REJECTED', '取引却下（事業）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'TRANSACTION_ACCOUNTANT_APPROVED', '取引承認（経理）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'TRANSACTION_ACCOUNTANT_REJECTED', '取引却下(経理)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'TRANSFER_BUSINESS_APPROVED', '振込承認（事業）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'TRANSFER_BUSINESS_REJECTED', '振込却下（事業）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'TRANSFER_ACCOUNTANT_APPROVED', '振込承認（経理）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'TRANSFER_ACCOUNTANT_REJECTED', '振込却下（経理）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'MFA_ENABLED', '多要素認証有効化', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'MFA_DISABLED', '多要素認証無効化', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'ACCOUNT_LOCKED', 'アカウントロック', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'ACCOUNT_UNLOCKED', 'アカウントロック解除', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'API_ACCESS', 'APIアクセス', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    code = VALUES(code),
    name = VALUES(name),
    updated_at = IF(
        code != VALUES(code) OR name != VALUES(name),
        CURRENT_TIMESTAMP,
        updated_at
    );

-- +goose Down
TRUNCATE TABLE audit_log_type;
